---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-budgie-test
# description will be included in the image's metadata
description: This is my personal OS image changing the gnome from bazzite to budgie desktop

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
 # 1. Remover a interface de usuário padrão do GNOME (mas mantendo o gerenciador GDM)
  - type: rpm-ostree
    remove:
      - gnome-shell
      - gnome-classic-session

  # 2. Instalar o Budgie Desktop e as ferramentas essenciais
  - type: rpm-ostree
    install:
      - budgie-desktop
      - budgie-desktop-view
      - budgie-control-center
      - budgie-backgrounds # Opcional: Papéis de parede oficiais do Budgie

  # 3. Gerenciamento de pacotes Flatpak iniciais (opcional)
  - type: default-flatpaks
    notify: true
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
